Add QR code component
blogic/ucentral-pwa pull request #33
Opened 2021-05-27 15:27 UTC by marcoow

This adds the `Uc::NetworkQrCode` for rendering the QR code with the network settings as well as sharing it via the Web Sharing API (Level 2).

<img width="403" alt="Bildschirmfoto 2021-05-27 um 17 24 54" src="https://user-images.githubusercontent.com/1510/119853708-b9a65600-bf10-11eb-8e8e-5fd05e0d0cad.png">

Unfortunately that API doesn't work in most browsers so in order to test this you'll need to be on Android Chrome or Safari Tech Preview. If the browser doesn't support sharing, we don't render the button.

closes #27

2021-05-27 16:28 UTC, BobrImperator requested changes

2021-05-27 16:28 UTC, BobrImperator commented on app/components/uc/network-qr-code.js
> +export default class CounterComponent extends Component {
```suggestion
export default class NetworkQrCodeComponent extends Component {
```

2021-05-27 16:28 UTC, BobrImperator commented on app/components/uc/network-qr-code.hbs
> +    local-class="auth__confirm-button"
Isn't css modules addon complaining about this?
I don't see the class to be present for this component. Usually it throws an error because of that.

Also consider renaming it.

2021-05-27 16:28 UTC, BobrImperator commented on app/components/uc/network-qr-code.js
> +  @task({ keepLatest: true })
would that make sense to set `maxConcurrency: 1`?

2021-05-27 16:28 UTC, BobrImperator commented on tests/integration/components/uc/network-qr-code-test.js
> +    this.owner.register(
I think it's a good idea to declare how many assertions we expect to be fired, especially in 'async' cases
```suggestion
  test("it draws the QR code when rendering", async function (assert) {
    assert.expect(1);
    this.owner.register(
```

2021-05-27 16:28 UTC, BobrImperator commented on app/components/uc/network-qr-code.js
> +export default class CounterComponent extends Component {
```suggestion
export default class NetworkQrCodeComponent extends Component {
```

2021-05-27 16:28 UTC, BobrImperator commented on app/components/uc/network-qr-code.hbs
> +{{#let (unique-id) as |canvasId|}}
```suggestion
```
This could potentially be removed since we're not querying the DOM anyway.

2021-05-28 07:15 UTC, marcoow commented on app/components/uc/network-qr-code.hbs
> +    local-class="auth__confirm-button"
right, that class shouldn't be added at all 👍

2021-05-28 07:18 UTC, marcoow commented on app/components/uc/network-qr-code.js
> +  @task({ keepLatest: true })
I think `maxConcurrency: 1` is implied in `drop` and `keepLatest`?

2021-05-28 07:21 UTC, BobrImperator commented on app/components/uc/network-qr-code.js
> +  @task({ keepLatest: true })
It didn't seem to be the case actually, even though `keepLatest` does seem to imply that in it's description.
http://ember-concurrency.com/docs/task-concurrency-advanced

Default concurrency is 3 and it keeps 3 tasks running and the rest is being dropped.

2021-05-28 07:27 UTC, marcoow commented on app/components/uc/network-qr-code.js
> +  @task({ keepLatest: true })
So that means `maxConcurrency: 1` would be additional documentation only in this case – not sure it's worth adding it?

2021-05-28 07:28 UTC, BobrImperator commented on app/components/uc/network-qr-code.js
> +  @task({ keepLatest: true })
Maybe it isn't I just thought I'd ask, there probably won't be any race conditions anyway.

2021-05-28 07:30 UTC, BobrImperator approved these changes

2021-05-28 07:30 UTC, merged